import Head from "next/head";
import { Box, Flex } from "@chakra-ui/react";
import useFetch from "../hook/useFetch";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex
        w="100vw"
        h="100vh"
        bg="hsl(218, 23%, 16%)"
        justifyContent="center"
        alignItems="center"
        color="white"
      ></Flex>
    </div>
  );
}
